config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get 'contact' => 'pages#contact'
  

  resources :albums do
    resources :photos
  end
  root :to => redirect('/home')

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, dependent: :destroy
  validates :name, presence: true
   
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  validates :caption, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!
  
  def new
  end

  def index
    @albums = Album.all
  end

  def create
    @album = Album.create(album_params)
    redirect_to albums_path
  end
  

  def update
    @album = Album.find params[:id]
    @album.update_attributes!(album_params)
    redirect_to album_path(@album)
  end

  def edit
    @album = Album.find params[:id]
  end
  def show
    id = params[:id]
    @album = Album.find(id)
  end
  private
  def album_params
      params.require(:album).permit(:name, :created, :comments)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to albums_path
  end

  def about
  end

  def contact
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!
  def new
    @album = Album.find(params[:album_id])
    @photo = @album.photos.build
  end
  
  def show
    
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def index
    @album = Album.find(params[:album_id])
    @photos = Photo.where(album_id: params[:album_id])
  end
  
  def update
    @photo = Photo.find params[:id]
    @photo.update_attributes!(photo_params)
    album = @photo.album
    redirect_to album_photos_path(album)
  end

  def create
     @album = Album.find(params[:album_id])
     @photo = @album.photos.create(photo_params)
     redirect_to album_photos_path
  end
  private 
  def photo_params
    params.require(:photo).permit(:caption, :snapped, :size)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/create.html.haml
%h1 Albums#create
%p Find me in app/views/albums/create.html.haml

app/views/albums/edit.html.haml
%h1 Albums#edit
%h2 Edit Album information
%p Find me in app/views/albums/edit.html.haml
= form_tag album_path(@album), :method => :put do
  = label :album, :name, 'Name'
  = text_field :album, :name
  = label :album , :created, 'Created on' 
  = date_select :album, :created
  = label :album, :comments, 'Comments'
  = text_area :album, :comments, size: "24x6"
  = submit_tag 'Save changes'

app/views/albums/index.html.haml
%h1 All Albums
%p Find me in app/views/albums/index.html.haml
%table#albums
  %thead
    %tr
      %th Name
      %th Created on
      %th Comments
      %th Links
      %th Photos
    %tbody
      - @albums.each do |album|
        %tr
          %td= album.name
          %td= album.created.strftime("%B %d,%y")
          %td= album.comments
          %td= link_to "More about #{album.name} album", album_path(album)
          %td= link_to "View photos", album_photos_path(album)
=link_to 'Add new album', new_album_path

app/views/albums/new.html.haml
%h1 Albums#new
%p Find me in app/views/albums/new.html.haml
%h2 Create a new Album
= form_tag albums_path, :method => :post do
  = label :album, :name, 'Name'
  = text_field :album, :name
  = label :album , :created, 'Created on' 
  = date_select :album, :created
  = label :album, :comments, 'Comments'
  = text_area :album, :comments, size: "24x6"
  = submit_tag 'Save changes'

app/views/albums/show.html.haml
%h2 Details about #{@album.name}
%ul#details
  %li
    Created:
    = @album.created
  %li
    Comments:
    =@album.comments
=link_to 'Edit album information', edit_album_path(@album)
=link_to 'Back to albums list', albums_path


app/views/albums/update.html.haml
%h1 Albums#update
%p Find me in app/views/albums/update.html.haml

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Albums and Photos
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #login
    -if user_signed_in?
      %p.welcome Signed in as #{current_user.email}.  Not you?
      =link_to 'Sign out', destroy_user_session_path, :method => :delete
    -else
      %p.login=link_to 'Sign up', new_user_registration_path
      =link_to 'Sign in', new_user_session_path
    =link_to "Home", home_path
    =link_to "About", about_path
    =link_to "Contact", contact_path
    =yield
    

app/views/pages/about.html.haml
%h1 Pages#about
%p This application was developed by Solomon Antony 
%p Team members are : Solomon Antony
%p This application tracks Albums and Photos.  Each album has many photos and a photo belongs to an album

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml
%p contact Solomon Antony at santony@murraystate.edu

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.haml

app/views/photos/create.html.haml
%h1 Photos#create
%p Find me in app/views/photos/create.html.haml

app/views/photos/edit.html.haml
%h1 Photos#edit
%p Find me in app/views/photos/edit.html.haml
%h2 Editing Photo
= form_tag album_photo_path(photo_id: @photo.id), :method => :put do
  = label :photo, :caption, 'Caption'
  = text_field :photo, :caption
  = label :photo , :snapped, 'Snapped on' 
  = date_select :photo, :snapped
  = label :photo, :size, 'size in pixels'
  = text_field :photo, :size, size: "24x6"
  = submit_tag 'Save changes'

app/views/photos/index.html.haml
%h1 Photos#index
%p 
="Photos from " + @album.name + " album" 
%table#photos
  %thead
    %tr
      %th Caption
      %th Snapped on
      %th Comments
      %th Size
    %tbody
      - @photos.each do |photo|
        %tr
          %td= photo.caption
          %td= photo.snapped.strftime("%B %d,%y")
          %td= photo.size
          %td= link_to "Edit photo information", edit_album_photo_path(photo.album, photo)
=link_to 'Add new photo', new_album_photo_path(@album)

app/views/photos/new.html.haml
%h1 Photos#new
%p 
="Adding a new photo to " + @album.name + " album" 
%h2 Create a new Photo
= form_tag album_photos_path(@album), :method => :post do
  = label :photo, :caption, 'Caption'
  = text_field :photo, :caption
  = label :photo , :snapped, 'Snapped on' 
  = date_select :photo, :snapped
  = label :photo, :size, 'size in pixels'
  = text_field :photo, :size, size: "24x6"
  = submit_tag 'Save changes'

app/views/photos/update.html.haml
%h1 Photos#update
%p Find me in app/views/photos/update.html.haml